"""add_bool_field_to_favorite_like_models_migration

Revision ID: 36781db418f5
Revises: 42f0141cfdb4
Create Date: 2025-03-26 11:55:29.292620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36781db418f5'
down_revision: Union[str, None] = '42f0141cfdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('reactions', sa.Column('is_liked', sa.Boolean(), nullable=False))
    op.drop_column('reactions', 'reaction_type')
    op.add_column('user_favorites', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_favorites', 'is_favorite')
    op.add_column('reactions', sa.Column('reaction_type', postgresql.ENUM('LIKE', 'DISLIKE', name='reactiontype'), autoincrement=False, nullable=False))
    op.drop_column('reactions', 'is_liked')
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
