"""orders modes status fix

Revision ID: 42f0141cfdb4
Revises: 00888209dd3f
Create Date: 2025-03-25 14:41:05.164453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f0141cfdb4'
down_revision: Union[str, None] = '00888209dd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_status_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_status_key', 'orders', ['status'])
    # ### end Alembic commands ###
