"""added_bool_fiels_in_favorite_movie_model_migration

Revision ID: 45a6c1d51039
Revises: 9a542b0e39dc
Create Date: 2025-03-25 18:43:57.969416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a6c1d51039'
down_revision: Union[str, None] = '9a542b0e39dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorites', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_favorites', 'is_favorite')
    # ### end Alembic commands ###
