"""chang_field_in_user_reaction_model_migration

Revision ID: 73e768ad6a32
Revises: 42f0141cfdb4
Create Date: 2025-03-25 16:51:20.531701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e768ad6a32'
down_revision: Union[str, None] = '42f0141cfdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('is_liked', sa.Boolean(), nullable=False))
    op.drop_column('reactions', 'reaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('reaction_type', postgresql.ENUM('LIKE', 'DISLIKE', name='reactiontype'), autoincrement=False, nullable=False))
    op.drop_column('reactions', 'is_liked')
    # ### end Alembic commands ###
