"""update_create_at_in_payments_and_delete_unique_in_orders

Revision ID: c1eeba6ee058
Revises: d36b15461f33
Create Date: 2025-03-25 04:43:26.069527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eeba6ee058'
down_revision: Union[str, None] = 'd36b15461f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_status_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_status_key', 'orders', ['status'])
    # ### end Alembic commands ###
