"""temp_migration

Revision ID: cb5b7e8d186d
Revises: b840367ab81c
Create Date: 2025-03-22 15:11:18.943290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5b7e8d186d'
down_revision: Union[str, None] = 'b840367ab81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_carts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'cart_id')
    )
    op.add_column('cart_items', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_cart_movie_constraint', 'cart_items', ['cart_id', 'movie_id'])
    op.create_foreign_key(None, 'cart_items', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint('unique_cart_movie_constraint', 'cart_items', type_='unique')
    op.drop_column('cart_items', 'movie_id')
    op.drop_table('user_carts')
    # ### end Alembic commands ###
