version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/app

  celery:
    build: .
    command: ["celery", "-A", "src.celery_app", "worker", "--loglevel=info", "-P", "solo"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env
    volumes:
      - .:/app

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d movies_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
